### ISSUE TITLE
make error when trying examples

### ISSUE THREAD

**Issue by qthuang** [sdsen/opened_extraction#13]
Having error when make after runnning run1.sh and run2.sh
<img width="1387" alt="截屏2022-12-01 16 44 34" src="https://user-images.githubusercontent.com/60091633/205165554-80c4fc89-5786-4d55-b807-6c12e38eac7d.png">

**Comment by OwenZhang001122** [comment]
For cilium, we can get phase 1 to work, but for phase 3 we can not generate the .c file and it extract a lot of files into the output folder, we are not sure if that is the correct situation....

**Comment by palanik1** [comment]
@qthuang Look for an ATTENTION Block in extracted.c.. There are two defs for ctl_array -- one in the .c and one in .h file. For xdpdecap, delete the map definition in extracted.c since we will be using the map definition in .h.

**Comment by palanik1** [comment]
@OwenZhang001122 Can you share the output folder and extracted.c file for Cilium?
