### ISSUE TITLE
Cilium missing .h files 

### ISSUE THREAD

**Issue by OwenZhang001122** [sdsen/opened_extraction#22]
We are trying to use the newest make files for extraction of cilium. We now face a problem that there is a missing library called bpf_features.h caused the make file error. 
We have already change the path of the make file to the examples/cilium where the libraries lies in, but this missing one isn't there....

Should this .h file given or should it be extracted from the tool? 
Thanks

![Screen Shot 2022-12-04 at 10 21 27 PM](https://user-images.githubusercontent.com/98358877/205542460-56f98866-6344-43a6-81dc-bef322fe164d.png)

![Screen Shot 2022-12-04 at 10 21 48 PM](https://user-images.githubusercontent.com/98358877/205542507-d8614555-5433-4e18-8c98-3c858d0a5b6f.png)

**Comment by sdsen** [comment]
@OwenZhang001122 can you pull in the new commits. It has new makefile for cilium, fixes some bugs, and  includes some missing files etc.

**Comment by OwenZhang001122** [comment]
Hi, We have checked but there is still no bpf_features.h file in the include/bpf/ path

**Comment by OwenZhang001122** [comment]
Please ignore the last comment, I think we resolve it
Thanks!

**Comment by sdsen** [comment]
closing based on last comment.
