### ISSUE TITLE
Add loading script for extracted code object file

### ISSUE THREAD

**Issue by sdsen** [sdsen/opened_extraction#23]
**Is your feature request related to a problem? Please describe.**
Need verifier code, as a starting piece, need a mechanism to attach the code to a virtual interface, and also clean out the interface once the testing of code is done.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
NA

**Additional context**
None

**Comment by sdsen** [comment]
Will reuse the output of https://github.com/palanik1/opened_transformation/issues/11

**Comment by palanik1** [comment]
Done..
