### ISSUE TITLE
ML-Based Equivalence Checking

### ISSUE THREAD

**Issue by Theophilusbenson** [sdsen/opened_extraction#44]
This feature builds on parallel attend to use OpenAI to create documentation. The goal of this feature is to build a lightweight equivalence check based on the text documentation of a function.  Ideally using techniques eg TTIDF and word2vec to determine if two functions could be equivalent based on their documentation.

**Comment by sdsen** [comment]
Closing as tracked here: https://github.com/eBPFDevSecTools/ebpf-projects-annotations/issues/24
