### ISSUE TITLE
Tracepoint_Probe Bug

### ISSUE THREAD

**Issue by NehaChowdhary** [sdsen/opened_extraction#49]
The tool is failing for the following files:

1. https://github.com/iovisor/bcc/blob/master/examples/tracing/biolatpcts.py
2. https://github.com/iovisor/bcc/blob/master/examples/tracing/hello_fields.py
3. https://github.com/iovisor/bcc/blob/master/examples/tracing/kvm_hypercall.py
4. https://github.com/iovisor/bcc/blob/master/examples/tracing/trace_fields.py
5. https://github.com/iovisor/bcc/blob/master/examples/tracing/urandomread.py

They all have tracepoint_probe/raw_tracepoint_probe as functions.

We created a 'bcc' folder in 'opened_extraction/examples' and added all the segregated bcc .c files and the respective python loader files. Then created two folders in 'opened_extraction/op' named 'commented_bcc' and 'txl_bcc'.
Inside the docker container on running **python3 src/annotator.py -o op/bcc/txl_bcc -s examples/bcc -c op/bcc/commented_bcc -t op/bcc/bcc.function_file_list.json -u op/bcc/bcc.struct_file_list.json** we are getting the following error:

**Traceback (most recent call last):
File "/root/src/annotator.py", line 306, in
create_code_comments(txl_func_file, bpf_helper_file, cmt_op_dir, isCilium)
File "/root/src/annotator.py", line 170, in create_code_comments
cmt.parseTXLFunctionOutputFileForComments(xmlFile, opFile, srcFile, helperdict, map_update_fn, map_read_fn)
File "/root/src/code_commentor.py", line 143, in parseTXLFunctionOutputFileForComments
output= funcName.split('(')[-2].split(" ")[-2]
IndexError: list index out of range**

@sdsen @palanik1

**Comment by NehaChowdhary** [comment]
> @NehaChowdhary Just to confirm..are you running the annotator on the segregated .c files or bcc .py files?

@palanik1 Sir we're running on the segregated .c files.

**Comment by palanik1** [comment]
ok...thanks for confirming..Can you share sample txl files where things are getting stuck..

**Comment by usatpath01** [comment]
[txl_files_bcc.zip](https://github.com/sdsen/opened_extraction/files/10382027/txl_files_bcc.zip)
@palanik1 Please find the attached sample txl files.

**Comment by palanik1** [comment]
@NehaChowdhary @usatpath01 Can you check if the patch fixes the issue with TRACEPOINT.

**Comment by NehaChowdhary** [comment]
> @NehaChowdhary @usatpath01 Can you check if the patch fixes the issue with TRACEPOINT.

I ran the patched code and it is running for all files. The function-with-docs.txt file also has the functions which were earlier causing an error.
@palanik1

**Comment by sdsen** [comment]
Closing.
