### ISSUE TITLE
Add BU student comments to asset

### ISSUE THREAD

**Issue by sdsen** [sdsen/opened_extraction#54]
**Is your feature request related to a problem? Please describe.**
As part of course project, EECS 528 BU students have generated docStrings for parts of cilium codebase. We should create a db with the docstrings and modify  code_comment.py to read that db for generating comment_stubs.

**Comment by sdsen** [comment]
@palanik1 merged the PR. please add author info as discussed, and then close this issue.

**Comment by palanik1** [comment]
Done.
