### ISSUE TITLE
OPENED-Extracted Programs for Merging

### ISSUE THREAD

**Issue by LCastanheira-1** [sdsen/opened_extraction#62]
It would be good to get a few sample programs extracted by opened so that we can try to merge the very same programs we are extracting

**Comment by sdsen** [comment]
@LCastanheira-1 please check https://github.com/sdsen/opened_extraction/tree/main/op  they are examples of extracted functions we will add more. All of them compile.

**Comment by palanik1** [comment]
@LCastanheira-1 To clarify, look for cilium_* and katran_* folders under the op folder for extracted code.

**Comment by sdsen** [comment]
closing for now.
