### ISSUE TITLE
Normalize comment formats between different files

### ISSUE THREAD

**Issue by palanik1** [sdsen/opened_extraction#78]
Currently there are two json formats that OPENED uses while generating code annotation stubs. Plan is to standardise format and move older format json to newer one.

**Comment by palanik1** [comment]
Old format
- Katran
- Cilium
New format
- mptm
- vbpf
- bcc
- bpf-filter
- rate-limiter

**Comment by sdsen** [comment]
@palanik1 is this a issue with human annotation?

**Comment by palanik1** [comment]
Yes...and the stubs that get generated between different versions of the code.

**Comment by sdsen** [comment]
@palanik1 is this fixed now?

**Comment by palanik1** [comment]
Done..
